configured a default value as function param for getCommandOrCtrlKey
user-focus/marvin-utils pull request #6
Opened 2023-10-18 17:40 UTC by abhijithhegde

#1 function will return default values or custom values on call

2023-10-19 16:30 UTC, abhijithhegde commented
@devcer could you please merge this?

2023-10-20 05:07 UTC, devcer commented on command-or-ctrl-key/src/index.ts
> +export const getCommandOrCtrlKey = ({
* create a `src/constants.ts` file
* Define a `DEFAULT_CONFIG = {.. your config}` 
* Import and pass it as a config `export const getCommandOrCtrlKey = (config = DEFAULT_CONFIG) =>{`
* update related tests as well

2023-10-20 05:07 UTC, devcer commented on command-or-ctrl-key/src/index.ts
> +const defaultKey = getCommandOrCtrlKey();
test these using unit tests.

2023-10-20 05:08 UTC, devcer requested changes
Need some changes

2023-10-20 18:03 UTC, abhijithhegde commented
Hey, I have updated the code! please check once

2023-10-22 04:29 UTC, devcer approved these changes

2023-10-22 04:29 UTC, merged